baseURL = 'https://teuder.github.io/notes/'
title = 'Masaki E. Tsuda'
theme = 'book'

# for github pages
publishDir = "docs" 

# Language
languageCode = "ja-JP"
DefaultContentLanguage = "ja"
hasCJKLanguage = true

# Book configuration
disablePathToLower = true
enableGitInfo = true

# Code highlight
pygmentsStyle = 'monokailight'
pygmentsCodeFences = true

#Other
disableKinds = ['taxonomy', 'taxonomyTerm']




[params]
  # (Optional, default 6) Set how many table of contents levels to be showed on page.
  # Use false to hide ToC, note that 0 will default to 6 (https://gohugo.io/functions/default/)
  # You can also specify this parameter per page in front matter
  BookToC = 3

  # (Optional, default none) Set leaf bundle to render as side menu
  # When not specified file structure and weights will be used
  # BookMenuBundle = '/menu'

  # (Optional, default docs) Specify section of content to render as menu
  # You can also set value to '*' to render all sections to menu
  BookSection = '*'

  # (Optional) This value is duplicate of $link-color for making active link highlight in menu bundle mode
  # BookMenuBundleActiveLinkColor = '\#004ed0'

  # Set source repository location.
  # Used for 'Last Modified' and 'Edit this page' links.
  BookRepo = 'https://github.com/teuder/notes'

  # Enable "Edit this page" links for 'doc' page type.
  # Disabled by default. Uncomment to enable. Requires 'BookRepo' param.
  # Path must point to 'content' directory of repo.
  BookEditPath = 'edit/master/content'

  # Configure the date format used on the pages
  # - In git information
  # - In blog posts
  # BookDateFormat = 'Jan 2, 2006'
  BookDateFormat = '2006-01-02'

  # (Optional, default true) Enables search function with lunr.js, 
  # Index is built on fly, therefore it might slowdown your website.
  BookSearch = true
